### ISSUE TITLE
catchPanic() prints to stdout on some semi-valid cases

### ISSUE THREAD

**Issue by matjam** [anaskhan96/soup#13]
libraries should not catch panic() and then print to stdout.

If I have the following code

```go
th := row.Find("th")
if th.Error == nil && th.Text() == "Service Expiry Date" {
    ...
}
```

and the call to `row.Find("th")` returns a structure with nil FirstChild member of Pointer struct, then soup will panic, catch the panic, and print to stdout.

By catching the panic, it makes it super hard to figure out what is causing the panic because all I got when running my program was this:

```
2017/12/18 11:17:56 Error occurred in Text() : runtime error: invalid memory address or nil pointer dereference
```

however if I comment out the `defer catchPanic("Text()")` call, then I get a much more helpful error:

```
DEBUG: DEBUG: &{0xc0422408c0 <nil> <nil> 0xc042240930 0xc042240a10 3 th th  [{ align right} { width 200}]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x688cdb]

goroutine 1 [running]:
github.com/anaskhan96/soup.Root.Text(0xc0422409a0, 0x7a7f94, 0x2, 0x0, 0x0, 0xc0420123f0, 0x63)
        C:/Users/chrome/Development/go/src/github.com/anaskhan96/soup/soup.go:219 +0xbb
main.fetchDate(0xc042052400, 0x1f)
        C:/Users/chrome/Development/go/src/gitlab.corp.xxx.com/se/shcheck/cmd/shcheck/main.go:96 +0x8e6
main.main()
        C:/Users/chrome/Development/go/src/gitlab.corp.xxx.com/se/shcheck/cmd/shcheck/main.go:112 +0x23d
```

which then if I look at soup.go line 219, i see

```go
	k := r.Pointer.FirstChild
checkNode:
	if k.Type != html.TextNode {
```

and it is now clear to me that r.Pointer.FirstChild is nil, and I need to check that it is not nil before calling Text().

However, you should be checking that value in your library, and returning `string, error`, in my opinion.

**Comment by anaskhan96** [comment]
Thank you for bringing this to my attention. Catching panics and printing them to stdout was something that issue #4 gave rise to, although I agree it wasn't a good decision at all. However, with the merge of PR #10, the `catchPanic()` function served as a redundant one, as the `SetDebug()` function took care of which mode the user wanted to program in.
I'll be making a commit fixing this.
