### ISSUE TITLE
[BUG]: Search classes with spaces fails every time (even in the weather example you provided)

### ISSUE THREAD

**Issue by Fef0** [anaskhan96/soup#24]
Hi, I tried your weather example and it always trows an "invalid memory address". I tried to reproduce the same bug with another website and it can actually search only those classes without any spaces inside of them. I don't know why but your parser stopped understanding spaces.
I added a fmt.Println() function in order to print the only class search with spaces (grid), that's the code:
```
package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/anaskhan96/soup"
)

func main() {
	fmt.Printf("Enter the name of the city : ")
	city, _ := bufio.NewReader(os.Stdin).ReadString('\n')
	city = city[:len(city)-1]
	cityInURL := strings.Join(strings.Split(city, " "), "+")
	url := "https://www.bing.com/search?q=weather+" + cityInURL
	resp, err := soup.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	doc := soup.HTMLParse(resp)
	grid := doc.Find("div", "class", "b_antiTopBleed b_antiSideBleed b_antiBottomBleed")
	fmt.Println("Print grid:", grid)
	heading := grid.Find("div", "class", "wtr_titleCtrn").Find("div").Text()
	conditions := grid.Find("div", "class", "wtr_condition")
	primaryCondition := conditions.Find("div")
	secondaryCondition := primaryCondition.FindNextElementSibling()
	temp := primaryCondition.Find("div", "class", "wtr_condiTemp").Find("div").Text()
	others := primaryCondition.Find("div", "class", "wtr_condiAttribs").FindAll("div")
	caption := secondaryCondition.Find("div").Text()
	fmt.Println("City Name : " + heading)
	fmt.Println("Temperature : " + temp + "˚C")
	for _, i := range others {
		fmt.Println(i.Text())
	}
	fmt.Println(caption)
}
```

And that's the output:
```
Enter the name of the city : New York
Print grid: {<nil>  element `div` with attributes `class b_antiTopBleed b_antiSideBleed b_antiBottomBleed` not found}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x61d1f5]

goroutine 1 [running]:
github.com/anaskhan96/soup.findOnce(0x0, 0xc42005be68, 0x3, 0x3, 0xc420050000, 0x4aa247, 0xc420261e00)
	/home/fef0/go/src/github.com/anaskhan96/soup/soup.go:304 +0x315
github.com/anaskhan96/soup.Root.Find(0x0, 0x0, 0x0, 0x6e1e60, 0xc420242070, 0xc42005be68, 0x3, 0x3, 0x0, 0x0, ...)
	/home/fef0/go/src/github.com/anaskhan96/soup/soup.go:120 +0x8d
main.main()
	/home/fef0/Code/Go/Test/Test.go:26 +0x4e3
exit status 2
```
If you notice in the second line it was impossible to found the grid, but in facts it happens only because there are spaces in the class name.
I hope you can fix that as soon as possible, bye for now!

**Comment by danielnovais92** [comment]
I think I have the same issue, I'm doing:
`newsDivs := doc.FindAll("div", "class", "media mt-15")`

But mine is weirder... It works well on Windows 10 running with GoLand but has this error on a server running CentOS 7 (although different versions of Go):
> go version go1.9.3 windows/amd64
> go version go1.8 linux/amd64

**Comment by danielnovais92** [comment]
Somehow I managed to make it work. I should be using `FindAllStrict ` (and that is working), but just `FindAll ` worked for months..

**Comment by cskonopka** [comment]
FindAllStrict also worked for me.

**Comment by greenpipig** [comment]
i think i have this issue too,hope author can fix it sooner,thx

**Comment by anaskhan96** [comment]
Hey guys, sorry for the 2+ year delay - work can be exhausting :/
This [commit](https://github.com/anaskhan96/soup/commit/ef9333abbd58649bc7e30410001e2bc2458be3e1) fixes the weather example.

It's been almost a year since `Find` and `FindAll`'s purpose had been changed to matching any word in a phrase separated by a whitespace, and their previous purpose (matching the exact phrase) had been bestowed upon `FindStrict` and `FindAllStrict`. You can view this [CHANGELOG](https://github.com/anaskhan96/soup/blob/master/CHANGELOG.md) for the details.
