### ISSUE TITLE
Empty strings throw errors on Text()

### ISSUE THREAD

**Issue by nick-stocks** [anaskhan96/soup#25]
When doing a FindAll(“td”), then calling Text() on a result, a null pointer error is thrown whenever an empty/nil value is encountered in the slice.

“runtime error: invalid memory address or nil pointer dereference
errorString”

An error object should be returned instead, or an empty string.

**Comment by iJebus** [comment]
I think this issue is still live, or at least a related issue exists. My code is doing a `FindNextElementSibling()` on a `Root` that may be empty, and I'm getting panics. 

Not a huge deal and can be worked around, but kinda tedious.

**Comment by anaskhan96** [comment]
Almost a year and the discussion gone's stale + this has been fixed in the commit mentioned above.
Closing this unless this issue arises again.
