### ISSUE TITLE
Proposal: Add an "Empty" func to Root that would make it easier to tell when a query didn't return results

### ISSUE THREAD

**Issue by gdholtslander** [anaskhan96/soup#29]
Right now I suppose you would do this by checking if error was non-nil and then check the error to see if it contained "not found", which you would only know about if you read the source code of this project 😄

I think what I am proposing is to add something that does that check for you in the library. Maybe something like:

```go
func (r Root) Empty() bool {
    if r.Error == nil {
         return false
    }
    return strings.Contains(string(r.Error), "not found")
}
```

Is this something other people would see as valuable? I would use it sorta like this:

```go
main := doc.Find("section", "class", "gramb")
if main.Empty() {
  return errors.New("No results for this query")
}
defs := main.FindAll("span", "class", "ind")
// Other processing here
```

Right now I'm just checking if main.Error is non nil and returning no results. Would just be nice (I think) to have a cleaner interface around it.

If you think this is worth doing I'd love to take a crack at it!

Thanks for this library, it's immensely helpful to my side project 😄

**Comment by gholtslander-va** [comment]
My specific use case is I have a script that scrapes a dictionary site for word definitions. If someone puts in a word that doesn't exist on that site it doesn't any of the particular thing I'm looking up in my code example above, so it is an empty selector.

**Comment by gholtslander-va** [comment]
An example implementation I added to my own downstream copy of soup: 

```go
// Empty returns true if the DOM query that produced it
// was not found in the HTML string.
func (r Root) Empty() bool {
	// Can't convert nil to string so need to apply this case
	if r.Error == nil {
		return false
	}
	if strings.Contains(r.Error.Error(), "not found") {
		return true
	}
	return false
}
```

**Comment by anaskhan96** [comment]
I understand your concern, and you have actually raised a valid question.

However, having an `Empty()` method for `Root` just to check if the error raised is "not found" would be setting a precedent for having other different methods for different kinds of errors. Right now, the library is in its infancy so most of the errors being generated are "not found" ones, but in later stages, as the library develops, there may be different kinds of errors being encountered.

A better solution would be to have an enum of errors, so new errors can be added as they are encountered and checked efficiently.

An example code would look like:
```go
main := doc.Find("section", "class", "gramb")
if main.Error == soup.NotFound {
    // proceed accordingly
}
```

**Comment by gholtslander-va** [comment]
I can't assign this issue to myself apparently but I'd take a crack at it if I could

**Comment by anaskhan96** [comment]
Sure, go ahead and try it out :)

**Comment by gdholtslander** [comment]
This is fixed now
