### ISSUE TITLE
log.Fatal

### ISSUE THREAD

**Issue by kryptodev** [anaskhan96/soup#4]
Hi,

Is it possible for you to replace log.Fatal instances with something else that returns an error instead?

It feels unfair if the entire program shuts down because soup couldn't find an element, and so on. I would rather like to handle the error when it cannot find something or it cannot parse html etc.

Thank you, been using this. :)

**Comment by anaskhan96** [comment]
Go is known for returning an extra error variable from a function (example `http.Get()` function), but the reason I didn't implement it was because I wanted the syntax to be identical to BeautifulSoup.
I'll be finding a way around this to implement better error handling :)

**Comment by kynrai** [comment]
Can you panic instead and defer a recovery to log the error and move on? Not sure if that would solve the exact problem here but it's a common go pattern
