### ISSUE TITLE
Hello~ I'm Student in KwangWoon University city of Seoul. Korea 

### ISSUE THREAD

**Issue by lionking6792** [anaskhan96/soup#40]
Hello! I'm Korean university student. If nothing is uncomfortable to you, I want to commit for 'soup' . I'm not a proffessional programer so, I can't commit difficult coding...

But, I can commit your repository More Examples Of Soup ! 
or, I can translate some guidelines. 

If you are Okay to it, I can Do it for a month.. and I will pull request for you.
Is it Okay me to do Write Examples of 'Soup' or some translation for guidelines or your repository

Please reply to me !! :) I will work very hard!!

I'm not very skillful at English so, I'm sorry if you can't read this English.. 

Sincerly, lionking6792

**Comment by mzpqnxow** [comment]
@lionking6792 you should write some translations and then pull request them. If they are not accepted, put them in a gist

**Comment by anaskhan96** [comment]
Hi @lionking6792, you're more than welcome to write examples/translation guidelines. I look forward to your PR :)

**Comment by anaskhan96** [comment]
Closing this since this has gone stale.
