### ISSUE TITLE
In the examples file weather.go element not found

### ISSUE THREAD

**Issue by avto727** [anaskhan96/soup#49]
Hello. help me, please.
Code:
package main

import (
"bufio"
"fmt"
"log"
"os"
"strings"

"github.com/anaskhan96/soup"
)

func main() {
	fmt.Printf("Enter the name of the city : ")
	city, _ := bufio.NewReader(os.Stdin).ReadString('\n')
	city = city[:len(city)-1]
	cityInURL := strings.Join(strings.Split(city, " "), "+")
	url := "https://www.bing.com/search?q=weather+" + cityInURL
	resp, err := soup.Get(url)
	if err != nil {
		log.Fatal(err)
	}
	doc := soup.HTMLParse(resp)
	fmt.Println(doc)
	grid := doc.Find("div", "class", "b_antiTopBleed b_antiSideBleed b_antiBottomBleed")
	fmt.Println("grid = ", grid)
	heading := grid.Find("div", "class", "wtr_titleCtrn").Find("div").Text()

----------------------------------------------------------------------------------------
GOROOT=C:\Go #gosetup
GOPATH=C:\Users\User\go\src\soup;C:\Users\User\go #gosetup
C:\Go\bin\go.exe build -o C:\Users\User\AppData\Local\Temp\___go_build_weather_go.exe C:\Users\User\go\src\soup\weather.go #gosetup
C:\Users\User\AppData\Local\Temp\___go_build_weather_go.exe #gosetup
Enter the name of the city : moscow
{0xc0002600e0 html <nil>}
grid =  {<nil>  element `div` with attributes `class b_antiTopBleed b_antiSideBleed b_antiBottomBleed` not found}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x6628dc]

goroutine 1 [running]:
github.com/anaskhan96/soup.findOnce(0x0, 0xc000471e70, 0x3, 0x3, 0xc000190000, 0xc000471b58, 0x468093)
	C:/Users/User/go/src/soup/src/github.com/anaskhan96/soup/soup.go:392 +0x31c
github.com/anaskhan96/soup.Root.Find(0x0, 0x0, 0x0, 0x760a00, 0xc000153820, 0xc000471e70, 0x3, 0x3, 0x0, 0x0, ...)
	C:/Users/User/go/src/soup/src/github.com/anaskhan96/soup/soup.go:167 +0x94
main.main()
	C:/Users/User/go/src/soup/weather.go:27 +0x5ef

Process finished with exit code 2

**Comment by anaskhan96** [comment]
Hi, [this comment](https://github.com/anaskhan96/soup/issues/24#issuecomment-696961538) provides the resolution
