### ISSUE TITLE
How can I find with class and get attribute?

### ISSUE THREAD

**Issue by UedaTakeyuki** [anaskhan96/soup#56]
Hello,

How can I use the following python bs **find** on your soup? Thank you for your suggestion!

```
Find("div", "class", "toggleVisible")["id"]
```

**Comment by bajro17** [comment]
`Find("div", "class", "toggleVisible").Attrs()["id"]` I guess you ask for this

**Comment by UedaTakeyuki** [comment]
Hi Bajro17,

It's working completely! Thank you!!!
