### ISSUE TITLE
Find() ret Root field value Pointer maybe nil

### ISSUE THREAD

**Issue by micheal0929** [anaskhan96/soup#58]
`rsp, err := soup.Get(pSp.pageQueue[pSp.pageIndex])`
	       `if err != nil {
			log.Printf("get page : %s, err : %s", pSp.pageQueue[pSp.pageIndex], err)
		}`
		`doc := soup.HTMLParse(rsp)`
		`pageExist := doc.Find("div", "class", "page")`
just like this 
type Root struct {
	Pointer   *html.Node
	NodeValue string
	Error     error
}
pageExist type is Root 
Pointer maybe nil,so not suggest using like this 
`doc.Find("div", "class", "tags").FindAll("span", "class", "tag-item")`
sometimes may cause panic
better use like this:
`
pageExist := doc.Find("div", "class", "page")`
`if pageExist.Pointer == nil {
	return//or do something else
}`
`aLinks := pageExist.FindAll("a")
`

**Comment by anaskhan96** [comment]
Thank you for your input on code quality.
Closing this as there's no issue wrt the library brought up.
