### ISSUE TITLE
Feature Request: User Defined Headers

### ISSUE THREAD

**Issue by yamamushi** [anaskhan96/soup#9]
Loving this library so far :-)

It would be really useful to be able to define our own headers, like user-agent for example. 

Then I'd be able to use this for sites that require auth :-)

**Comment by anaskhan96** [comment]
That sounds like a good idea. I'll try implementing this as a second argument to the `soup.Get()` function in an upcoming update.

**Comment by anaskhan96** [comment]
Resolved by #11
